ci: swap order of line length and trailing lines checks in lint workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -11,20 +11,6 @@ jobs:
         with:
           lfs: true
 
-      - name: Check line length of lox files
-        run: |
-          # Run check_line_length and capture output
-          output=$(make check_line_length)
-          
-          # Check if the output contains "ERROR"
-          if echo "$output" | grep -q "ERROR"; then
-            echo "::error::Line length check failed. Some files have lines exceeding the maximum length."
-            echo "$output"
-            exit 1
-          else
-            echo "Line length check passed."
-          fi
-
       - name: Check empty trailing lines in lox files
         run: |
           # Run check_empty_trailing_lines and capture output
@@ -37,4 +23,18 @@ jobs:
             exit 1
           else
             echo "Empty trailing lines check passed."
+          fi
+  
+      - name: Check line length of lox files
+        run: |
+          # Run check_line_length and capture output
+          output=$(make check_line_length)
+          
+          # Check if the output contains "ERROR"
+          if echo "$output" | grep -q "ERROR"; then
+            echo "::error::Line length check failed. Some files have lines exceeding the maximum length."
+            echo "$output"
+            exit 1
+          else
+            echo "Line length check passed."
           fi
